version: '3.8'

services:
  mysql-standalone1:
    image: mysql:5.6
    environment:
    - MYSQL_ROOT_PASSWORD=root 
    - MYSQL_DATABASE=springbootdb 
  springboot-docker-container:
   image: springboot-docker-container
   ports:
     - 8080:8080
   build:
     context: ./
     dockerfile: Dockerfile
   depends_on:
     - mysql-standalone1       
 